baud_rate: 9600
com_port: /dev/ttyUSB0
invert_sliders: true
noise_reduction: default
slider_mapping:
  0:
  - master
  1:
  - Discord.exe
  2:
  - Fmod Audio
  - eurotrucks2
  - enlisted
  - zerohour
  3:
  - Firefox
  - firefox
  4:
  - Spotify
