baud_rate: 9600
com_port: /dev/ttyUSB0
invert_sliders: true
noise_reduction: default
slider_mapping:
  0:
  - master
  1:
  - discord
  2:
  - eurotrucks2
  - enlisted
  3:
  - spotify
  4:
  - firefox
